In [31]:
import numpy as np
import copy

In [32]:
from board import Board
from tictactoe import TicTacToe
from agent import Agent, RandomPlayer
from treenode import TreeNode
from mcts import MCTS

In [41]:
def play_game():
    board = Board()
    game = TicTacToe(board)
    player1 = RandomPlayer(game)
    player2 = RandomPlayer(game)
    players = [player1, player2]
    current_player = 0

    while not game.is_over:
        game.board.print_board()
        move = players[current_player].get_move(game)
        print(move)
        if move is None:
            print("Player ", current_player, " should play, but the board is full")
            break
        if not board.board[move] == 0:
            print("Invalid move: ", move)
            break
        game.make_move(move)
        current_player = 1 - current_player

    game.board.print_board()
    print("Game over. Winner: ", game.check_winner())

play_game()


[0 0 0]
[0 0 0]
[0 0 0]
7
[0 0 0]
[0 0 0]
[0 1 0]
2
[ 0  0 -1]
[0 0 0]
[0 1 0]
3
[ 0  0 -1]
[1 0 0]
[0 1 0]
0
[-1  0 -1]
[1 0 0]
[0 1 0]
6
[-1  0 -1]
[1 0 0]
[1 1 0]
4
[-1  0 -1]
[ 1 -1  0]
[1 1 0]
5
[-1  0 -1]
[ 1 -1  1]
[1 1 0]
8
[-1  0 -1]
[ 1 -1  1]
[ 1  1 -1]
Game over. Winner:  -1


In [ ]:
def play_game_with_mcts():
    board = Board()
    game = TicTacToe(board)
    player1 = RandomPlayer(game)
    player2 = Agent(game, MCTS(game))
    players = [player1, player2]
    current_player = 0

    while not game.is_over:
        game.board.print_board()
        move = players[current_player].get_move(game)
        print(move)
        if move is None:
            print("Player ", current_player, " should play, but the board is full")
            break
        if not board.board[move] == 0:
            print("Invalid move: ", move)
            break
        game.make_move(move)
        current_player = 1 - current_player

    game.board.print_board()
    print("Game over. Winner: ", game.check_winner())