In [18]:
import numpy as np
import copy

In [19]:
from board import Board
from tictactoe import TicTacToe
from agent import Agent, RandomPlayer
from treenode import TreeNode
from mcts import MCTS


In [27]:
def play_game():
    board = Board()
    game = TicTacToe(board)
    player1 = RandomPlayer(game)
    player2 = RandomPlayer(game)
    players = [player1, player2]
    current_player = 0

    while not game.is_over:
        game.board.print_board()
        move = players[current_player].get_move(game)
        print(move)
        if not move:
            print("Player ", current_player, " should play, but the board is full")
            break
        if not game.board.is_valid_move(move):
            print("Invalid move: ", move)
            break
        game.make_move(move)
        current_player = 1 - current_player

    game.board.print_board()
    print("Game over. Winner: ", game.get_winner())

play_game()


[0 0 0]
[0 0 0]
[0 0 0]
5


AttributeError: 'Board' object has no attribute 'is_valid_move'